name: AustinLive
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1b=h1de35cc_1
  - pip=19.0.3=py37_0
  - python=3.7.2=haf84260_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.8.0=py37_0
  - sqlite=3.26.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appnope==0.1.0
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - chardet==3.0.4
    - citipy==0.0.5
    - decorator==4.3.2
    - defusedxml==0.5.0
    - entrypoints==0.3
    - geojson==2.4.1
    - gmaps==0.8.4
    - idna==2.8
    - ipykernel==5.1.0
    - ipython==7.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10
    - jsonschema==3.0.1
    - jupyter-client==5.2.4
    - jupyter-core==4.4.0
    - kdtree==0.16
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - notebook==5.7.5
    - numpy==1.16.2
    - pandas==0.24.1
    - pandocfilters==1.4.2
    - parso==0.3.4
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pygments==2.3.1
    - pyrsistent==0.14.11
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pyzmq==18.0.1
    - requests==2.21.0
    - send2trash==1.5.0
    - six==1.12.0
    - terminado==0.8.1
    - testpath==0.4.2
    - tornado==6.0.1
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2
prefix: /anaconda3/envs/AustinLive

